import java.util.Properties

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.hilt)
    alias(libs.plugins.ksp)
}

val localProps = Properties().apply {
    rootProject.file("local.properties").takeIf { it.exists() }?.inputStream()?.use { load(it) }
}

android {
    namespace = "com.crsk.openclaw"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.crsk.openclaw"
        minSdk = 26
        targetSdk = 34
        versionCode = 12
        versionName = "0.6.2"

        ndk {
            abiFilters += "arm64-v8a"
        }

    }

    packaging {
        jniLibs.useLegacyPackaging = true
    }

    // Bundled archives (npm.tgz, shell scripts) ship pre-compressed; don't re-zip.
    androidResources {
        noCompress.addAll(listOf("apk", "sh", "tgz", "node_modules"))
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
        // Variant for macrobenchmark runs. Production-like (non-debuggable, R8 off so the
        // benchmark module can resolve symbols), debug-signed so it installs without keystore
        // setup, and matches release so startup timings are representative.
        create("benchmark") {
            initWith(getByName("release"))
            isMinifyEnabled = false
            isShrinkResources = false
            isDebuggable = false
            signingConfig = signingConfigs.getByName("debug")
            matchingFallbacks += listOf("release")
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        compose = true
        aidl = true
        buildConfig = true
    }

    testOptions {
        // Android's Log.d/i etc. throw "not mocked" in JVM unit tests by default.
        // returnDefaultValues makes them silent no-ops, which is fine for our use.
        unitTests.isReturnDefaultValues = true
    }
}

// Compose Compiler is enabled by the kotlin.compose plugin. Strong skipping is the
// default since Compose 1.7 — composables become skippable unless their parameters
// are explicitly @Stable-violating. Metrics + reports dump stability CSVs into
// build/compose_compiler so we can audit unstable params.
composeCompiler {
    reportsDestination = layout.buildDirectory.dir("compose_compiler")
    metricsDestination = layout.buildDirectory.dir("compose_compiler")
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.lifecycle.runtime.compose)
    implementation(libs.androidx.lifecycle.process)
    implementation(libs.androidx.activity.compose)

    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.graphics)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.compose.material3)
    implementation(libs.compose.material.icons)
    implementation(libs.navigation.compose)

    implementation(libs.hilt.android)
    ksp(libs.hilt.compiler)
    implementation(libs.hilt.navigation.compose)

    implementation(libs.datastore.preferences)
    implementation(libs.coroutines.android)
    implementation("org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.7")
    // Real iOS-style backdrop blur for the composer and nav bar.
    implementation("dev.chrisbanes.haze:haze:1.2.2")
    // SF Symbol-esque line icons. Replaces Material Icons where we want a less Material feel.
    implementation("com.composables:icons-lucide:1.0.0")
    implementation(libs.coil.compose)
    implementation(libs.coil.svg)
    implementation(libs.androidx.browser)
    implementation(libs.security.crypto)

    implementation("dev.rikka.shizuku:api:13.1.5")
    implementation("dev.rikka.shizuku:provider:13.1.5")
    implementation("org.nanohttpd:nanohttpd:2.3.1")
    implementation(libs.okhttp)
    // Installs the bundled Baseline Profile at first launch so AOT-compiled
    // critical paths (startup → first chat frame) are fast on cold start.
    // A profile is generated by the benchmark variant + a separate
    // :macrobenchmark module (Android Studio: Run > Generate Baseline Profile).
    // Without that module, this dep is still safe: it's a tiny runtime that
    // becomes a no-op when no profile is shipped.
    implementation("androidx.profileinstaller:profileinstaller:1.3.1")

    debugImplementation(libs.compose.ui.tooling)

    testImplementation(libs.junit)
    testImplementation(libs.json)
    testImplementation(libs.coroutines.test)
}

// The prebuilt Node.js .so files are not in git — they come from a GitHub
// Release via scripts/fetch-node-libs.sh. Fail early with instructions
// instead of producing an APK that crashes at startup with no libnode.so.
val checkNodeLibs by tasks.registering {
    doFirst {
        val libnode = file("src/main/jniLibs/arm64-v8a/libnode.so")
        if (!libnode.exists() || libnode.length() < 1_000_000) {
            throw GradleException(
                "Missing prebuilt Node.js libraries in app/src/main/jniLibs/. " +
                    "Run ./scripts/fetch-node-libs.sh from the repo root, then rebuild."
            )
        }
    }
}
tasks.named("preBuild") { dependsOn(checkNodeLibs) }
